//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1586.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class archive
{

	private archiveAdd[] addField = new archiveAdd[] {};

	private archive[] addedArchivesField = new archive[] {};

	private packageContentXml[] xmlField = new packageContentXml[] {};

	private string pathField = string.Empty;

	private string createIfNotExistField = string.Empty;

	private string typeField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("add", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
	public archiveAdd[] add {
		get {
			return this.addField;
		}
		set {
			this.addField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("archive")]
	public archive[] addedArchives {
		get {
			return this.addedArchivesField;
		}
		set {
			this.addedArchivesField = value;
		}
	}

	[System.Xml.Serialization.XmlElementAttribute("xml", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageContentXml[] xml {
		get {
			return this.xmlField;
		}
		set {
			this.xmlField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string path {
		get {
			return this.pathField;
		}
		set {
			this.pathField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string createIfNotExist {
		get {
			return this.createIfNotExistField;
		}
		set {
			this.createIfNotExistField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string type {
		get {
			return this.typeField;
		}
		set {
			this.typeField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class archiveAdd
{

	private string sourceField = string.Empty;

	private string valueField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string source {
		get {
			return this.sourceField;
		}
		set {
			this.sourceField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value {
		get {
			return this.valueField;
		}
		set {
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class package
{

	private packageMetadata[] metadataField = new packageMetadata[] {};

	private packageColors[] colorsField = new packageColors[] {};

	private packageContent[] contentField = new packageContent[] {};

	private string versionField = string.Empty;

	private string idField = string.Empty;

	private string targetField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("metadata", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageMetadata[] metadata {
		get {
			return this.metadataField;
		}
		set {
			this.metadataField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("colors", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageColors[] colors {
		get {
			return this.colorsField;
		}
		set {
			this.colorsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("content", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageContent[] content {
		get {
			return this.contentField;
		}
		set {
			this.contentField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string version {
		get {
			return this.versionField;
		}
		set {
			this.versionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string id {
		get {
			return this.idField;
		}
		set {
			this.idField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string target {
		get {
			return this.targetField;
		}
		set {
			this.targetField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageMetadata
{

	private string nameField = string.Empty;

	private string descriptionField = string.Empty;

	private packageMetadataVersion[] versionField = new packageMetadataVersion[] {};

	private packageMetadataAuthor[] authorField = new packageMetadataAuthor[] {};

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string name {
		get {
			return this.nameField;
		}
		set {
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public XmlNode description {
		get {
			var dummy = new XmlDocument();
			return dummy.CreateCDataSection(this.descriptionField);
		}
		set {
			if (value == null)
			{
				this.descriptionField = null;
				return;
			}
			this.descriptionField = value.Value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("version", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageMetadataVersion[] version {
		get {
			return this.versionField;
		}
		set {
			this.versionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("author", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageMetadataAuthor[] author {
		get {
			return this.authorField;
		}
		set {
			this.authorField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageMetadataVersion
{

	private string majorField = string.Empty;

	private string minorField = string.Empty;

	private string tagField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string major {
		get {
			return this.majorField;
		}
		set {
			this.majorField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string minor {
		get {
			return this.minorField;
		}
		set {
			this.minorField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string tag {
		get {
			return this.tagField;
		}
		set {
			this.tagField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageMetadataAuthor
{

	private string displayNameField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string displayName {
		get {
			return this.displayNameField;
		}
		set {
			this.displayNameField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageColors
{

	private string iconBackgroundField = string.Empty;

	private packageColorsHeaderBackground[] headerBackgroundField = new packageColorsHeaderBackground[] {};

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string iconBackground {
		get {
			return this.iconBackgroundField;
		}
		set {
			this.iconBackgroundField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("headerBackground", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
	public packageColorsHeaderBackground[] headerBackground {
		get {
			return this.headerBackgroundField;
		}
		set {
			this.headerBackgroundField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageColorsHeaderBackground
{

	private string useBlackTextColorField = string.Empty;

	private string valueField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string useBlackTextColor {
		get {
			return this.useBlackTextColorField;
		}
		set {
			this.useBlackTextColorField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value {
		get {
			return this.valueField;
		}
		set {
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageContent
{

	private archive[] archiveField = new archive[] {};

	private packageContentText[] textField = new packageContentText[] {};

	private packageContentXml[] xmlField = new packageContentXml[] {};

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("archive")]
	public archive[] archive {
		get {
			return this.archiveField;
		}
		set {
			this.archiveField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("text", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageContentText[] text {
		get {
			return this.textField;
		}
		set {
			this.textField = value;
		}
	}

	[System.Xml.Serialization.XmlElementAttribute("xml", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public packageContentXml[] xml
	{
		get {
			return this.xmlField;
		}
		set {
			this.xmlField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageContentText
{

	private string addField = string.Empty;

	private string pathField = string.Empty;

	private string createIfNotExistField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string add {
		get {
			return this.addField;
		}
		set {
			this.addField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string path {
		get {
			return this.pathField;
		}
		set {
			this.pathField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string createIfNotExist {
		get {
			return this.createIfNotExistField;
		}
		set {
			this.createIfNotExistField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class packageContentXml
{
	private xmlAdd[] addField = new xmlAdd[] {};

	private string pathField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("add", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
	public xmlAdd[] add {
		get {
			return this.addField;
		}
		set {
			this.addField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string path {
		get {
			return this.pathField;
		}
		set {
			this.pathField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class xmlAdd
{

	private string xPathField = string.Empty;

	private xmlItem[] itemsField = new xmlItem[] {};

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
	public xmlItem[] item {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string xpath {
		get {
			return this.xPathField;
		}
		set {
			this.xPathField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class xmlItem
{
	private string valueField = string.Empty;

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value {
		get {
			return this.valueField;
		}
		set {
			this.valueField = value;
		}
	}
}